# Generated by Django 5.0.7 on 2025-10-02 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nome da empresa')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título da vaga')),
                ('employment_type', models.CharField(choices=[('CLT', 'Efetivo (CLT)'), ('PJ', 'Pessoa Jurídica (PJ)')], max_length=10, verbose_name='Tipo de emprego')),
                ('work_mode', models.CharField(choices=[('PRESENCIAL', 'Presencial'), ('REMOTO', 'Remoto'), ('HIBRIDO', 'Híbrido')], max_length=12, verbose_name='Tipo de trabalho')),
                ('opening_date', models.DateField(verbose_name='Data de abertura')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('benefits', models.JSONField(blank=True, default=list, verbose_name='Benefícios (lista)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='jobs.company')),
            ],
            options={
                'ordering': ['-opening_date', '-created_at'],
            },
        ),
    ]
